Refactor to clarify flow of search-bar component
mwmbl/front-end-original pull request #24
Opened 2022-07-23 14:00 UTC by sarayourfriend

This is a slight refactor to help clarify the flow of the search-bar component and how it works. It was previously relying on dispatching the submit event to initialize the search when the component was connected, but this allows it to do so in a more typical non-event bus driven way.

It also moves certain things into their own methods like the search event dispatch and the layout change. This makes it easier to read the flow of the handle search routine.

This PR should not result in any change of behavior, with or without reduced motion.

2022-07-25 09:51 UTC, ColinEspinas commented
Just read the code and it seems good, will test and merge if okay later today.

2022-07-26 18:53 UTC, ColinEspinas requested changes

2022-07-26 18:53 UTC, ColinEspinas commented on src/components/organisms/search-bar.js
> +  _setDisplayMode(mode) {
Use double underscore instead of single for "private" methods. Do you have a specific reason why you did it this way I am open for advices.

2022-07-26 19:05 UTC, sarayourfriend commented on src/components/organisms/search-bar.js
> +  _setDisplayMode(mode) {
Nope! Is there an operational different with double underscores for web components? I only typically see two underscores in PHP and Python magic methods or long meta-names that need extra separation.

2022-07-26 19:07 UTC, ColinEspinas commented on src/components/organisms/search-bar.js
> +  _setDisplayMode(mode) {
That's just something I've seen done and have done since a while while waiting for the `#` private methods to be available in all browsers.

2022-07-26 19:13 UTC, sarayourfriend commented on src/components/organisms/search-bar.js
> +  _setDisplayMode(mode) {
Cool, sure thing. Happy to follow those conventions :slightly_smiling_face:

2022-07-26 19:15 UTC, sarayourfriend commented on src/components/organisms/search-bar.js
> +  _setDisplayMode(mode) {
Updated in https://github.com/mwmbl/front-end/pull/24/commits/cb3ed8715a0a24aacf07752bac219b6c4ae65581

2022-07-26 19:20 UTC, ColinEspinas approved these changes
Thanks, those are some silly conventions but help to keep things kinda clean. Thanks again for your contribution!

2022-07-26 19:20 UTC, merged